#!/bin/csh -f

foreach k ($*)

	if (-e $k.orig) then
		if (-w $k) then
			echo "Le fichier '"$k"' est en check-out."
		else
			set nomFichierDiff = `dirname $k`/diff`basename $k`
			set n=`GENERATE $k.orig $nomFichierDiff-* | diff - $k | wc -l`
			if ("$n" == "0") then
				echo "Le fichier '"$k"' est cohérent."
			else
				echo "Le fichier '"$k"' est incohérent."
			endif
		endif
	else
		echo "Le fichier '"$k"' est cohérent."

	endif

end
